{{- if and .Values.webhook.enabled .Values.webhook.patch.enabled .Values.webhook.patch.rbac.create (not .Values.webhook.certManager.enabled) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kaniop.fullname" . }}-webhook
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "kaniop.webhook.labels" . | nindent 4 }}
    {{- with .Values.webhook.patch.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kaniop.fullname" . }}-webhook
subjects:
  - kind: ServiceAccount
    name: {{ include "kaniop.webhook.patch.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
