{{- if and .Values.webhook.enabled .Values.webhook.patch.enabled (not .Values.webhook.certManager.enabled) -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kaniop.fullname" . }}-webhook-create-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- with .Values.webhook.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "kaniop.webhook.labels" . | nindent 4 }}
    {{- with .Values.webhook.patch.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ttlSecondsAfterFinished: 0
{{- if gt (int .Values.webhook.patch.createSecretJob.activeDeadlineSeconds) 0 }}
  activeDeadlineSeconds: {{ .Values.webhook.patch.createSecretJob.activeDeadlineSeconds }}
{{- end }}
  template:
    metadata:
      name: {{ include "kaniop.fullname" . }}-webhook-create-secret
    {{- if .Values.webhook.patch.podAnnotations }}
      annotations: {{ toYaml .Values.webhook.patch.podAnnotations | nindent 8 }}
    {{- end }}
      labels:
        {{- include "kaniop.webhook.labels" . | nindent 8 }}
        {{- with .Values.webhook.patch.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- if .Values.webhook.patch.priorityClassName }}
      priorityClassName: {{ .Values.webhook.patch.priorityClassName }}
    {{- end }}
      {{- with .Values.webhook.patch.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: create
          image: {{ .Values.webhook.patch.image.repository }}:{{ .Values.webhook.patch.image.tag }}
          imagePullPolicy: {{ .Values.webhook.patch.image.pullPolicy }}
          args:
            - create
            - --host={{ include "kaniop.fullname" . }}-webhook,{{ include "kaniop.fullname" . }}-webhook.$(POD_NAMESPACE).svc,{{ include "kaniop.fullname" . }}-webhook.$(POD_NAMESPACE).svc.cluster.local
            - --namespace=$(POD_NAMESPACE)
            - --secret-name={{ include "kaniop.fullname" . }}-webhook-cert
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- if .Values.webhook.patch.extraEnvs }}
            {{- toYaml .Values.webhook.patch.extraEnvs | nindent 12 }}
          {{- end }}
          {{- if .Values.webhook.patch.createSecretJob.securityContext }}
          securityContext: {{ toYaml .Values.webhook.patch.createSecretJob.securityContext | nindent 12 }}
          {{- end }}
          {{- if .Values.webhook.patch.createSecretJob.resources }}
          resources: {{ toYaml .Values.webhook.patch.createSecretJob.resources | nindent 12 }}
          {{- end }}
      restartPolicy: OnFailure
      serviceAccountName: {{ include "kaniop.webhook.patch.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.webhook.patch.serviceAccount.automountServiceAccountToken }}
    {{- if .Values.webhook.patch.nodeSelector }}
      nodeSelector: {{ toYaml .Values.webhook.patch.nodeSelector | nindent 8 }}
    {{- end }}
    {{- if .Values.webhook.patch.tolerations }}
      tolerations: {{ toYaml .Values.webhook.patch.tolerations | nindent 8 }}
    {{- end }}
    {{- if .Values.webhook.patch.securityContext }}
      securityContext: {{ toYaml .Values.webhook.patch.securityContext | nindent 8 }}
    {{- end }}
{{- end }}
