{{- if and .Values.webhook.enabled .Values.webhook.patch.enabled .Values.webhook.patch.serviceAccount.create (not .Values.webhook.certManager.enabled) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kaniop.webhook.patch.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "kaniop.webhook.labels" . | nindent 4 }}
    {{- with .Values.webhook.patch.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.webhook.patch.serviceAccount.automountServiceAccountToken }}
{{- end }}
